### ISSUE TITLE
This dependency was not found:  * expose?$!expose?jQuery!jquery in ./src/main.js

### ISSUE THREAD

**Issue by agungid** [prograhammer/vue-pizza#4]
Hi. I have a problem when include jquery. Please solve it. thank you
![error jquery](https://user-images.githubusercontent.com/11351024/29129113-f295206a-7d4f-11e7-81e9-1084835f6f47.png)

**Comment by prograhammer** [comment]
You'll need to install the expose loader first and add to your dev dependencies: 

    npm install expose-loader --save-dev 

You can read more about it here: https://github.com/webpack-contrib/expose-loader

**Comment by agungid** [comment]
I have done the expose-loader installation.
Where i should put config?
Module: {
  Rules: [{
          Test: require.resolve ('jquery'),
          Use: [{
              Loader: 'expose-loader',
              Options: '$'
          }]
      }]
}

**Comment by agungid** [comment]
Thanks. It works
